### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by keyscores** [phadej/relaxed-json#13]
@phadej  I really like relaxed-json, but it's breaking in browser implementations and numbers in key names is an issue for me. 

Are you maintaining this repo? It would be preferable that you say in the Readme that this is not being maintained in favor of HJSON.

**Comment by phadej** [comment]
Well, it's "maintained". In a sense it works for me. I'm happy to take PRs, if it doesn't work for someone else.

About number keys: it should be configurable.

**Comment by keyscores** [comment]
@phadej thanks. There is already a fix for one of the issues:
https://github.com/phadej/relaxed-json/issues/9
Can you incorporate that one?

**Comment by phadej** [comment]
Just published a 1.0.1, sorry it took so long
